POST  http://localhost:5000/soma
Content-Type: application/json

{

"numero1":299,
"numero2": 1

}

###

GET http://localhost:5000/calculos

###

DELETE http://localhost:5000//deletar/5fec6ff3-4b40-4627-a7c6-0afad49ce883
