POST  http://localhost:5000/soma
Content-Type: application/json

{

"numero1":5,
"numero2": 5

}

###

GET http://localhost:5000/calculos

###

DELETE http://localhost:5000//deletar/bead04d6-15d8-4488-af56-7fe70f103d75

###

PUT http://localhost:5000//editar/3f36d4aa-080d-4b3e-99b9-7805b3ce4fdb
Content-Type: application/json

{

"numero1":7,
"numero2": 7

}
